name: Update Docker Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/queuebit:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/queuebit:latest ${{ secrets.DOCKER_USERNAME }}/queuebit:${{ github.sha }}

      # Step 4: Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/queuebit:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/queuebit:${{ github.sha }}

      # Step 5: Deploy to server
      - name: Restart container
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{ secrets.DOCKER_IP }}
          username : ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: |
            cd /DockerContainer/
            ./deply.sh
              
        
